-- Add migration script here
ALTER TABLE DAIKOKU.WALLET 
MODIFY updated_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE DAIKOKU.ACCOUNT 
ADD balance DECIMAL(10, 2) NOT NULL default 0.0,
ADD balance_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
MODIFY updated_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE DAIKOKU.TRANSACTION 
MODIFY updated_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
