-- Lookup tables


-- Lookup Account type
CREATE TABLE IF NOT EXISTS DAIKOKU.LU_ACCOUNT_TYPE (
    id TINYINT UNSIGNED AUTO_INCREMENT,
    value VARCHAR(10) NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO DAIKOKU.LU_ACCOUNT_TYPE(value)
VALUES ("Asset"), ("Liability"), ("Expense"), ("Income"), ("Equity");

-- Lookup Transaction type
CREATE TABLE IF NOT EXISTS DAIKOKU.LU_TRANSACTION_TYPE (
    id TINYINT UNSIGNED AUTO_INCREMENT,
    value VARCHAR(6) NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO DAIKOKU.LU_TRANSACTION_TYPE (value)
VALUES ("Debit"), ("Credit");

-- Wallet
CREATE TABLE IF NOT EXISTS DAIKOKU.WALLET (
    id INT UNSIGNED AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

-- Account
CREATE TABLE IF NOT EXISTS DAIKOKU.ACCOUNT (
    id INT UNSIGNED AUTO_INCREMENT,
    wallet_id INT UNSIGNED NOT NULL,
    type_id TINYINT UNSIGNED NOT NULL,

    name VARCHAR(255) NOT NULL,
    created_date TIMESTAMP NOT NULL default CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (wallet_id) REFERENCES DAIKOKU.WALLET(id)
);

-- Transaction
CREATE TABLE IF NOT EXISTS DAIKOKU.TRANSACTION (
    id INT UNSIGNED AUTO_INCREMENT,
    account_id INT UNSIGNED NOT NULL,
    type_id TINYINT UNSIGNED NOT NULL,

    amount DECIMAL(10, 2) NOT NULL,
    execution_date TIMESTAMP NOT NULL default CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES DAIKOKU.ACCOUNT(id)
);

